export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>RecruitList</title>
  <base href="https://mrxshion.github.io/candidate/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">[_nghost-ng-c4067569060]{position:relative}[_nghost-ng-c4067569060]:before{content:"";position:absolute;inset:0;background-image:url(https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);background-size:cover;background-position:center;opacity:.5;z-index:-1;height:97vh}.login-card[_ngcontent-ng-c4067569060]{position:relative;width:350px;margin:auto;padding:20px;border-radius:10px;box-shadow:0 4px 8px #0003;background-color:#fff;text-align:center;z-index:1}.login-card-in[_ngcontent-ng-c4067569060]{width:350px;margin:auto;padding:20px;border-radius:10px;background-color:#fff0;text-align:center}.login-card[_ngcontent-ng-c4067569060]   h2[_ngcontent-ng-c4067569060]{margin-bottom:15px}.login-card[_ngcontent-ng-c4067569060]   label[_ngcontent-ng-c4067569060]{display:block;text-align:left;margin-top:10px;font-weight:700}.login-card[_ngcontent-ng-c4067569060]   input[_ngcontent-ng-c4067569060]{width:100%;max-width:100%;padding:8px;margin-top:5px;border:1px solid #ccc;border-radius:5px;box-sizing:border-box}.login-card[_ngcontent-ng-c4067569060]   button[_ngcontent-ng-c4067569060]{width:100%;padding:10px;margin-top:15px;border:none;background-color:#007bff;color:#fff;border-radius:5px;cursor:pointer;font-size:16px}.login-card[_ngcontent-ng-c4067569060]   button[_ngcontent-ng-c4067569060]:disabled{background-color:#ccc;cursor:not-allowed}.error-message[_ngcontent-ng-c4067569060]{color:red;margin-top:10px}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["submit","input","compositionstart","compositionend"],["blur"]);</script>
  <app-root ng-version="19.2.5" ngh="1" ng-server-context="ssg"><router-outlet></router-outlet><app-login _nghost-ng-c4067569060 ngh="0"><div _ngcontent-ng-c4067569060 class="login-card-in"></div><div _ngcontent-ng-c4067569060 class="login-card-in"></div><div _ngcontent-ng-c4067569060 class="login-card-in"></div><div _ngcontent-ng-c4067569060 class="login-card-in"></div><div _ngcontent-ng-c4067569060 class="login-card"><h2 _ngcontent-ng-c4067569060>Login</h2><form _ngcontent-ng-c4067569060 novalidate class="ng-untouched ng-pristine ng-invalid" jsaction="submit:;"><label _ngcontent-ng-c4067569060>Email</label><input _ngcontent-ng-c4067569060 type="email" formcontrolname="email" required value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><label _ngcontent-ng-c4067569060>Password</label><input _ngcontent-ng-c4067569060 type="password" formcontrolname="password" required value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><!----><button _ngcontent-ng-c4067569060 type="submit" disabled>Log in</button></form></div></app-login><!----></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-L3X3UEIE.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"14":"t0"},"c":{"14":[]}},{"c":{"0":[{"i":"c4067569060","r":1}]}}]}</script></body></html>`;